# Generated by Django 3.0 on 2020-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20200224_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='ptime',
            field=models.DateTimeField(null=True),
        ),
    ]
